# UTF-8 编码设置
systemProp.file.encoding=UTF-8
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=14455
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=14455
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.https.nonProxyHosts=localhost|127.0.0.1
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.java.home=C:\\Program Files\\Java\\graalvm-jdk-25.0.3+9.1
org.gradle.java.installations.paths=C:\\Program Files\\Java\\zulu17.58.21-ca-jdk17.0.15-win_x64,C:\\Program Files\\Java\\zulu21.44.17-ca-fx-jdk21.0.8-win_x64,C:\\Program Files\\Java\\graalvm-jdk-21.0.10+8.1,C:\\Program Files\\Java\\graalvm-jdk-25.0.3+9.1
# Fabric 版本配置
minecraft_version=1.21.8
loader_version=0.16.14

# Fabric API 版本
fabric_version=0.134.0+1.21.8

# Mod 信息
mod_version=0.3.1
maven_group=neoproxy
archives_base_name=NeoLinkMC
neolinkapi_version=7.2.3
