modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="neolinkmc"
version="${version}"
displayName="NeoLinkMC"
description='''NeoLinkMC opens integrated Minecraft worlds through NeoLink.'''
authors="NeoProxy Team"
logoFile="assets/neolinkmc/icon.png"

[[mixins]]
config="neolinkmc.mixins.json"

[[dependencies.neolinkmc]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.neolinkmc]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
